name: eqlite
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  dropdown_button2: 2.0.0
  easy_debounce: 2.0.1
  equatable: 2.0.5
  shimmer: ^3.0.0
  sliding_action_button: ^0.0.7
  device_info_plus:
  csv: ^5.0.2
#  google_mlkit_barcode_scanning: ^0.14.1
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_rating_bar: 4.0.1
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  flutter_secure_storage: 8.0.0
  google_fonts: 4.0.3
  intl: 0.18.1
  image_picker:
  firebase_auth: ^4.0.0
  json_path: 0.6.2
  mime_type: 1.0.0
  page_transition: 2.0.4
  jumping_dot: ^0.0.7
  flutter_file_dialog: ^3.0.2
  flutter_echarts: ^2.5.0
  fl_chart:
  any_animated_button: ^0.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  fluttertoast: ^8.2.4
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  percent_indicator: 4.2.2
  pin_code_fields: 7.4.0
  provider: 6.0.4
  syncfusion_flutter_charts: ^24.1.41
  qr_code_scanner: ^1.0.1
  shared_preferences: 2.0.15
  share_plus:
  speech_to_text:
  flutter_html:
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  carousel_slider: ^5.0.0
  simple_gradient_text: 1.2.3
  smooth_page_indicator: 1.0.1
  static_map: ^0.3.1
  screenshot:
  web_socket_channel:
  sqflite: 2.2.6
  timeago: 3.2.2
  geocoding:
  geolocator:
  firebase_core: 2.32.0
  firebase_messaging:
  permission_handler: ^11.3.1
  url_launcher: 6.1.10
  google_maps_flutter:
  google_api_headers:
  flutter_image_compress: ^1.1.0
  google_places_flutter:
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
  cupertino_icons: ^1.0.6

dependency_overrides:
  http: ^1.2.1
google_api_headers:
    path: packages/google_api_headers


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/